import 'dart:math' as math;

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../htmltagstyles.dart';
import 'css_style.dart';
import 'image_builder_io.dart' if (dart.library.html) 'image_builder_web.dart'
    as image_builder;
import 'layout/layout_node.dart';
import 'mathml_builder.dart';
import 'span_grid.dart';

/// A laid-out block: its widgets plus the vertical margins it wants around
/// it. Margins are kept separate so adjacent sibling margins can collapse
/// (`max(bottom, top)`) like they do in a browser.
class _Block {
  final List<pw.Widget> widgets;
  final double marginTop;
  final double marginBottom;

  const _Block(this.widgets, {this.marginTop = 0, this.marginBottom = 0});
}

/// Result of joining sibling blocks: widgets with the collapsed spacing
/// between them, plus the outer margins of the first and last block.
class _Flow {
  final List<pw.Widget> widgets;
  final double top;
  final double bottom;

  const _Flow(this.widgets, this.top, this.bottom);
}

/// Mutable state while collecting inline spans for one line box.
class _InlineContext {
  final spans = <pw.InlineSpan>[];

  /// True at the start of a line, or after collapsible whitespace, so the
  /// next collapsible space is dropped.
  bool lastWasSpace = true;
}

/// [PdfBuilder] converts a tree of [LayoutNode]s into a list of [pw.Widget]s.
///
/// It traverses the render tree and creates corresponding PDF widgets (e.g.,
/// [pw.Container], [pw.RichText], [pw.Table]) based on the node type and its
/// computed [CSSStyle], following browser rules for whitespace collapsing,
/// vertical margin collapsing, list markers and table spans.
class PdfBuilder {
  /// The root node of the render tree.
  final LayoutNode root;

  /// Custom tag styles for checkbox customization.
  final HtmlTagStyle tagStyle;

  /// Fallback fonts for handling emojis and multiple languages.
  final List<pw.Font> fontFallback;

  /// Creates an instance of [PdfBuilder].
  ///
  /// [root] is the root [LayoutNode] generated by [HtmlParser].
  /// [tagStyle] provides custom styling options including checkbox icons.
  /// [fontFallback] provides fonts for special characters and emojis.
  PdfBuilder({
    required this.root,
    this.tagStyle = const HtmlTagStyle(),
    this.fontFallback = const [],
  });

  /// Depth of nested unordered lists (drives disc/circle/square markers).
  int _listDepth = 0;

  /// > 0 while building children of a horizontal flex row, where widgets
  /// must not request infinite width.
  int _rowDepth = 0;

  /// Content longer than this (in characters) is split into several
  /// [pw.RichText] widgets so it can flow across pages.
  static const int _chunkChars = 1500;

  pw.Font? _courier, _courierBold, _courierOblique, _courierBoldOblique;

  /// Builds the PDF widgets from the render tree.
  Future<List<pw.Widget>> build() async {
    final blocks = await _buildFlow(root.children, root.style);
    // The page margins already separate content from the page edge, so the
    // outermost leading/trailing margins are dropped.
    return _join(blocks).widgets;
  }

  // ---------------------------------------------------------------------------
  // Block flow
  // ---------------------------------------------------------------------------

  bool _isInlineLevel(LayoutNode node) {
    if (node.tagName == 'math') return !_isBlockMath(node);
    if (node.tagName == '#text' || node.tagName == 'br') return true;
    if (node.tagName == 'input') {
      return node.attributes['type'] == 'checkbox';
    }
    if (node.tagName == 'img') return node.style.display == Display.inline;
    return node.display == Display.inline;
  }

  /// Builds a sequence of sibling nodes, grouping consecutive inline-level
  /// nodes into anonymous line boxes.
  Future<List<_Block>> _buildFlow(
      List<LayoutNode> children, CSSStyle containerStyle) async {
    final blocks = <_Block>[];
    var inlineGroup = <LayoutNode>[];

    Future<void> flushInline() async {
      if (inlineGroup.isEmpty) return;
      final widgets = await _buildInlineRun(inlineGroup, containerStyle);
      inlineGroup = [];
      if (widgets.isNotEmpty) blocks.add(_Block(widgets));
    }

    for (final child in children) {
      if (child.display == Display.none) continue;
      if (_isInlineLevel(child)) {
        inlineGroup.add(child);
        continue;
      }
      await flushInline();
      final block = await _buildBlockNode(child);
      if (block != null) blocks.add(block);
    }
    await flushInline();
    return blocks;
  }

  /// Joins sibling blocks, inserting collapsed margins between them.
  _Flow _join(List<_Block> blocks) {
    final widgets = <pw.Widget>[];
    if (blocks.isEmpty) return const _Flow([], 0, 0);
    for (var i = 0; i < blocks.length; i++) {
      final block = blocks[i];
      if (i > 0) {
        final gap = math.max(blocks[i - 1].marginBottom, block.marginTop);
        if (gap > 0) widgets.add(pw.SizedBox(height: gap));
      }
      widgets.addAll(block.widgets);
    }
    return _Flow(widgets, blocks.first.marginTop, blocks.last.marginBottom);
  }

  Future<_Block?> _buildBlockNode(LayoutNode node) async {
    if (node.display == Display.none) return null;
    final style = node.style;
    final marginTop = style.margin?.top ?? 0;
    final marginBottom = style.margin?.bottom ?? 0;

    switch (node.tagName) {
      case 'math':
        final box = _buildMath(node);
        return _Block(
            [pw.Align(alignment: pw.Alignment.center, child: box.widget)],
            marginTop: math.max(marginTop, (style.fontSize ?? 12) * 0.5),
            marginBottom: math.max(marginBottom, (style.fontSize ?? 12) * 0.5));
      case 'img':
        return _Block([
          _horizontalMargins(_alignBlock(await _buildImage(node), style), style)
        ], marginTop: marginTop, marginBottom: marginBottom);
      case 'table':
        return _Block(await _buildTable(node),
            marginTop: marginTop, marginBottom: marginBottom);
      case 'hr':
        final rb = style.resolvedBorder;
        bool visible(pw.BorderSide s) => s.style.paint && s.width > 0;
        // First *visible* side: `border: 0; border-top: 1px solid` leaves
        // an invisible (non-null) bottom side.
        final side = rb == null
            ? const pw.BorderSide(width: 1, color: PdfColors.grey)
            : [rb.bottom, rb.top, rb.left, rb.right]
                .firstWhere(visible, orElse: () => rb.bottom);
        return _Block([
          _horizontalMargins(
              pw.Divider(
                height: side.width,
                thickness: side.width,
                color: side.color,
                borderStyle: side.style,
              ),
              style)
        ], marginTop: marginTop, marginBottom: marginBottom);
      case 'ul':
      case 'ol':
      case 'menu':
        return _buildList(node);
      case 'input':
      case 'br':
        return null;
    }

    if (node.display == Display.flex) {
      return _Block(await _buildFlex(node),
          marginTop: marginTop, marginBottom: marginBottom);
    }

    if (style.whiteSpace == WhiteSpace.pre ||
        style.whiteSpace == WhiteSpace.preWrap) {
      return _buildPreBlock(node);
    }

    return _buildContainerBlock(node);
  }

  /// A generic block container (div, p, h1, blockquote, li content, ...).
  Future<_Block?> _buildContainerBlock(LayoutNode node) async {
    final style = node.style;
    final flow = _join(await _buildFlow(node.children, style));
    return _decorateBlock(node, flow);
  }

  /// Applies padding, border, background, width and horizontal margins to
  /// already-built content, collapsing child margins through the box when
  /// it has no top/bottom padding or border.
  _Block? _decorateBlock(LayoutNode node, _Flow flow) {
    final style = node.style;
    final padding = style.padding ?? pw.EdgeInsets.zero;
    final border = style.resolvedBorder;
    final background = style.backgroundColor;

    bool sideVisible(pw.BorderSide? s) =>
        s != null && s.style.paint && s.width > 0;
    final hasTopEdge = padding.top > 0 || sideVisible(border?.top);
    final hasBottomEdge = padding.bottom > 0 || sideVisible(border?.bottom);

    var marginTop = style.margin?.top ?? 0;
    var marginBottom = style.margin?.bottom ?? 0;
    final widgets = <pw.Widget>[...flow.widgets];

    if (hasTopEdge) {
      if (flow.top > 0 && widgets.isNotEmpty) {
        widgets.insert(0, pw.SizedBox(height: flow.top));
      }
    } else {
      marginTop = math.max(marginTop, flow.top);
    }
    if (hasBottomEdge) {
      if (flow.bottom > 0 && widgets.isNotEmpty) {
        widgets.add(pw.SizedBox(height: flow.bottom));
      }
    } else {
      marginBottom = math.max(marginBottom, flow.bottom);
    }

    if (widgets.isEmpty) {
      // An empty box still shows its padding, border and background, e.g.
      // `<div style="border-bottom:1px solid">` separators.
      double edge(pw.BorderSide? side) => sideVisible(side) ? side!.width : 0.0;
      final boxHeight = style.height ??
          (padding.top +
              padding.bottom +
              edge(border?.top) +
              edge(border?.bottom));
      if (boxHeight > 0 &&
          (background != null || border != null || style.height != null)) {
        return _Block([
          _horizontalMargins(
              _maxWidth(
                  pw.Container(
                    width: style.width ?? _fullWidth,
                    height: boxHeight,
                    decoration: _boxDecoration(style),
                  ),
                  style),
              style)
        ], marginTop: marginTop, marginBottom: marginBottom);
      }
      return (marginTop > 0 || marginBottom > 0)
          ? _Block(const [], marginTop: marginTop, marginBottom: marginBottom)
          : null;
    }

    final needsBox = background != null ||
        border != null ||
        style.width != null ||
        style.maxWidth != null ||
        style.height != null;

    if (!needsBox) {
      final result = <pw.Widget>[];
      if (padding.top > 0) result.add(pw.SizedBox(height: padding.top));
      for (final w in widgets) {
        result.add(_horizontalInsets(w, padding.left, padding.right, style));
      }
      if (padding.bottom > 0) result.add(pw.SizedBox(height: padding.bottom));
      return _Block(result, marginTop: marginTop, marginBottom: marginBottom);
    }

    if (_isSmall(node)) {
      final content = widgets.length == 1
          ? widgets.first
          : pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: widgets);
      pw.Widget box = pw.Container(
        width: style.width ?? _fullWidth,
        height: style.height,
        padding: padding,
        decoration: _boxDecoration(style),
        child: content,
      );
      box = _maxWidth(box, style);
      if (style.width != null || style.maxWidth != null) {
        box = _alignBlock(box, style);
      }
      return _Block([_horizontalMargins(box, style)],
          marginTop: marginTop, marginBottom: marginBottom);
    }

    // Large blocks: decorate each child separately so the block can still
    // break across pages, drawing top/bottom edges as caps.
    final side = pw.Border(
      left: border?.left ?? pw.BorderSide.none,
      right: border?.right ?? pw.BorderSide.none,
    );
    final result = <pw.Widget>[];
    result.add(pw.Container(
      width: _fullWidth,
      height: padding.top,
      decoration: pw.BoxDecoration(
        color: background,
        border: pw.Border(
            top: border?.top ?? pw.BorderSide.none,
            left: side.left,
            right: side.right),
      ),
    ));
    for (final w in widgets) {
      result.add(pw.Container(
        width: _fullWidth,
        padding: pw.EdgeInsets.only(left: padding.left, right: padding.right),
        decoration: pw.BoxDecoration(color: background, border: side),
        child: w,
      ));
    }
    result.add(pw.Container(
      width: _fullWidth,
      height: padding.bottom,
      decoration: pw.BoxDecoration(
        color: background,
        border: pw.Border(
            bottom: border?.bottom ?? pw.BorderSide.none,
            left: side.left,
            right: side.right),
      ),
    ));
    return _Block(result.map((w) => _horizontalMargins(w, style)).toList(),
        marginTop: marginTop, marginBottom: marginBottom);
  }

  double? get _fullWidth => _rowDepth > 0 ? null : double.infinity;

  /// Caps a box at CSS `max-width` (it still fills up to that width).
  pw.Widget _maxWidth(pw.Widget child, CSSStyle style) {
    final max = style.maxWidth;
    if (max == null || _rowDepth > 0) return child;
    return pw.ConstrainedBox(
        constraints: pw.BoxConstraints(maxWidth: max), child: child);
  }

  /// Whether a block is small enough to be wrapped in a single non-spanning
  /// [pw.Container] (which cannot break across pages).
  bool _isSmall(LayoutNode node) {
    var chars = 0;
    var blocks = 0;
    var heavy = false;
    void walk(LayoutNode n) {
      chars += n.text?.length ?? 0;
      if (n.tagName == 'table' || n.tagName == 'pre' || n.tagName == 'img') {
        heavy = true;
      }
      if (n.tagName == 'li' || n.tagName == 'p' || n.tagName == 'div') {
        blocks++;
      }
      for (final c in n.children) {
        walk(c);
      }
    }

    walk(node);
    return !heavy && chars < 1200 && blocks < 12;
  }

  pw.Widget _horizontalMargins(pw.Widget child, CSSStyle style) {
    final left = style.margin?.left ?? 0;
    final right = style.margin?.right ?? 0;
    if (left <= 0 && right <= 0) return child;
    return pw.Padding(
        padding: pw.EdgeInsets.only(
            left: math.max(0, left), right: math.max(0, right)),
        child: child);
  }

  pw.Widget _horizontalInsets(
      pw.Widget child, double padLeft, double padRight, CSSStyle style) {
    final left = padLeft + math.max(0, style.margin?.left ?? 0);
    final right = padRight + math.max(0, style.margin?.right ?? 0);
    if (left <= 0 && right <= 0) return child;
    return pw.Padding(
        padding: pw.EdgeInsets.only(left: left, right: right), child: child);
  }

  /// Centers/right-aligns a fixed-size block per `margin: auto` or the
  /// inherited `text-align` (browsers align images in line boxes).
  pw.Widget _alignBlock(pw.Widget child, CSSStyle style) {
    if (_rowDepth > 0) return child;
    if (style.centerHorizontally == true ||
        style.textAlign == pw.TextAlign.center) {
      return pw.Align(alignment: pw.Alignment.topCenter, child: child);
    }
    if (style.textAlign == pw.TextAlign.right) {
      return pw.Align(alignment: pw.Alignment.topRight, child: child);
    }
    return child;
  }

  pw.BoxDecoration? _boxDecoration(CSSStyle style) {
    final border = style.resolvedBorder;
    if (style.backgroundColor == null && border == null) return null;
    final uniform = border != null &&
        _sameSide(border.top, border.right) &&
        _sameSide(border.top, border.bottom) &&
        _sameSide(border.top, border.left);
    return pw.BoxDecoration(
      color: style.backgroundColor,
      border: border,
      // Rounded corners are only supported with a uniform border.
      borderRadius: style.borderRadius != null &&
              style.borderRadius! > 0 &&
              (border == null || uniform)
          ? pw.BorderRadius.circular(style.borderRadius!)
          : null,
    );
  }

  bool _sameSide(pw.BorderSide a, pw.BorderSide b) =>
      a.width == b.width && a.color == b.color && a.style == b.style;

  // ---------------------------------------------------------------------------
  // Inline content
  // ---------------------------------------------------------------------------

  Future<List<pw.Widget>> _buildInlineRun(
      List<LayoutNode> nodes, CSSStyle blockStyle) async {
    final ctx = _InlineContext();
    for (final node in nodes) {
      await _collectInline(node, ctx, null);
    }
    return _richTextWidgets(ctx.spans, blockStyle);
  }

  /// Builds line boxes from inline [spans], splitting very long content
  /// into several widgets so it can flow across pages.
  List<pw.Widget> _richTextWidgets(
      List<pw.InlineSpan> input, CSSStyle blockStyle) {
    final spans = _nbspToSpace(_trimTrailingSpace(input));
    if (spans.isEmpty) return [];

    final textAlign = blockStyle.textAlign ?? pw.TextAlign.left;
    pw.Widget make(List<pw.InlineSpan> chunk) => pw.RichText(
          overflow: pw.TextOverflow.span,
          text: pw.TextSpan(children: chunk),
          textAlign: textAlign,
          textDirection: blockStyle.textDirection,
        );

    final totalLen = _spanLength(spans);
    if (totalLen > 2000) {
      return _splitSpans(spans, _chunkChars).map(make).toList();
    }
    return [make(spans)];
  }

  int _spanLength(List<pw.InlineSpan> spans) {
    var total = 0;
    for (final s in spans) {
      total += s is pw.TextSpan ? (s.text?.length ?? 0) : 1;
    }
    return total;
  }

  /// Renders non-breaking spaces as plain spaces (many PDF fonts lack a
  /// U+00A0 glyph). Runs after trimming so `&nbsp;` is never collapsed away.
  List<pw.InlineSpan> _nbspToSpace(List<pw.InlineSpan> spans) => [
        for (final s in spans)
          if (s is pw.TextSpan && (s.text?.contains('\u00A0') ?? false))
            pw.TextSpan(
              text: s.text!.replaceAll('\u00A0', ' '),
              style: s.style,
              baseline: s.baseline,
              annotation: s.annotation,
            )
          else
            s
      ];

  /// Removes collapsible trailing whitespace (and drops a content-free run).
  List<pw.InlineSpan> _trimTrailingSpace(List<pw.InlineSpan> spans) {
    final result = [...spans];
    while (result.isNotEmpty) {
      final last = result.last;
      if (last is! pw.TextSpan) break;
      final text = last.text ?? '';
      final trimmed = text.replaceAll(RegExp(r' +$'), '');
      if (trimmed.isEmpty) {
        result.removeLast();
        continue;
      }
      if (trimmed != text) {
        result[result.length - 1] = pw.TextSpan(
          text: trimmed,
          style: last.style,
          baseline: last.baseline,
          annotation: last.annotation,
        );
      }
      break;
    }
    // Only ASCII whitespace is collapsible; Dart's trim() would also strip
    // U+00A0 and drop `<p>&nbsp;</p>` spacer lines.
    final hasContent = result.any((s) =>
        s is! pw.TextSpan ||
        (s.text ?? '').replaceAll(RegExp(r'[ \t\n\r\f]'), '').isNotEmpty);
    return hasContent ? result : const [];
  }

  Future<void> _collectInline(
      LayoutNode node, _InlineContext ctx, String? href) async {
    if (node.display == Display.none) return;

    if (node.tagName == 'br') {
      ctx.spans.add(pw.TextSpan(text: '\n', style: _mapTextStyle(node.style)));
      ctx.lastWasSpace = true;
      return;
    }

    if (node.tagName == 'input' && node.attributes['type'] == 'checkbox') {
      ctx.spans.add(pw.WidgetSpan(
        child: _buildCheckbox(node),
        baseline: _checkboxBaseline(node),
      ));
      ctx.lastWasSpace = false;
      return;
    }

    if (node.tagName == 'math') {
      final block = _isBlockMath(node);
      final box = _buildMath(node);
      // Display math nested in inline content still gets a line of its own.
      if (block && ctx.spans.isNotEmpty) {
        ctx.spans.add(const pw.TextSpan(text: '\n'));
      }
      // Put the formula's baseline on the text baseline.
      ctx.spans.add(pw.WidgetSpan(child: box.widget, baseline: -box.depth));
      if (block) ctx.spans.add(const pw.TextSpan(text: '\n'));
      ctx.lastWasSpace = block;
      return;
    }

    if (node.tagName == 'img') {
      ctx.spans.add(pw.WidgetSpan(child: await _buildImage(node)));
      ctx.lastWasSpace = false;
      return;
    }

    if (node.tagName == '#text') {
      final text = _processText(node.text ?? '', node.style, ctx);
      if (text.isEmpty) return;
      ctx.spans.add(pw.TextSpan(
        text: text,
        style: _mapTextStyle(node.style),
        baseline: _baselineShift(node.style),
        annotation: href != null ? pw.AnnotationUrl(href) : null,
      ));
      return;
    }

    final link = node.tagName == 'a' && node.attributes['href'] != null
        ? node.attributes['href']
        : href;
    for (final child in node.children) {
      await _collectInline(child, ctx, link);
    }
  }

  /// Applies `white-space` collapsing and `text-transform` to a text run.
  String _processText(String raw, CSSStyle style, _InlineContext ctx) {
    final ws = style.whiteSpace ?? WhiteSpace.normal;
    String text;
    if (ws == WhiteSpace.pre || ws == WhiteSpace.preWrap) {
      text = raw.replaceAll('\r\n', '\n').replaceAll('\t', '    ');
      if (text.isEmpty) return '';
      ctx.lastWasSpace = text.endsWith('\n');
    } else {
      if (ws == WhiteSpace.preLine) {
        text = raw
            .replaceAll('\r\n', '\n')
            .replaceAll(RegExp(r'[ \t\f]+'), ' ')
            .replaceAll(RegExp(r' ?\n ?'), '\n');
      } else {
        text = raw.replaceAll(RegExp(r'[ \t\n\r\f]+'), ' ');
      }
      if (ctx.lastWasSpace && text.startsWith(' ')) text = text.substring(1);
      if (text.isEmpty) return '';
      ctx.lastWasSpace = text.endsWith(' ') || text.endsWith('\n');
    }
    // Non-breaking spaces survive collapsing and trimming; [_nbspToSpace]
    // turns them into plain spaces once lines are assembled.
    return _transform(text, style.textTransform);
  }

  String _transform(String text, TextTransform? transform) {
    switch (transform) {
      case TextTransform.uppercase:
        return text.toUpperCase();
      case TextTransform.lowercase:
        return text.toLowerCase();
      case TextTransform.capitalize:
        return text.replaceAllMapped(RegExp(r'(^|[\s\-])(\S)'),
            (m) => '${m.group(1)}${m.group(2)!.toUpperCase()}');
      default:
        return text;
    }
  }

  double _baselineShift(CSSStyle style) {
    final size = style.fontSize ?? 12;
    switch (style.baselineShift) {
      case BaselineShift.superscript:
        return size * 0.45;
      case BaselineShift.subscript:
        return -size * 0.25;
      default:
        return 0;
    }
  }

  double _checkboxBaseline(LayoutNode node) {
    switch (node.style.verticalAlign) {
      case VerticalAlign.top:
        return 6;
      case VerticalAlign.bottom:
        return -2;
      case VerticalAlign.baseline:
        return 0;
      default:
        return -3;
    }
  }

  List<List<pw.InlineSpan>> _splitSpans(List<pw.InlineSpan> spans, int limit) {
    final result = <List<pw.InlineSpan>>[];
    var currentChunk = <pw.InlineSpan>[];
    int currentLen = 0;

    void flush() {
      if (currentChunk.isNotEmpty) result.add(currentChunk);
      currentChunk = [];
      currentLen = 0;
    }

    for (var span in spans) {
      if (span is pw.TextSpan) {
        String text = span.text ?? '';
        while (currentLen + text.length > limit) {
          // Break at a newline or space so words aren't cut in half.
          final room = limit - currentLen;
          var cut = text.lastIndexOf('\n', room);
          if (cut <= 0) cut = text.lastIndexOf(' ', room);
          if (cut <= 0) {
            if (currentChunk.isNotEmpty) {
              flush();
              continue;
            }
            cut = room.clamp(1, text.length);
          } else {
            cut += 1; // keep the separator on this chunk
          }
          currentChunk.add(pw.TextSpan(
            text: text.substring(0, cut).replaceAll(RegExp(r'\n$'), ''),
            style: span.style,
            baseline: span.baseline,
            annotation: span.annotation,
          ));
          flush();
          text = text.substring(cut);
        }
        if (text.isNotEmpty) {
          currentChunk.add(pw.TextSpan(
            text: text,
            style: span.style,
            baseline: span.baseline,
            annotation: span.annotation,
          ));
          currentLen += text.length;
        }
      } else {
        if (currentLen + 1 > limit) flush();
        currentChunk.add(span);
        currentLen += 1;
      }
    }

    flush();
    return result;
  }

  // ---------------------------------------------------------------------------
  // Text style
  // ---------------------------------------------------------------------------

  static const _monospaceFamilies = {
    'courier',
    'courier new',
    'monospace',
    'consolas',
    'menlo',
    'monaco',
    'lucida console',
    'source code pro',
    'ui-monospace',
    'sfmono-regular',
  };

  pw.Font? _fontFor(CSSStyle style) {
    final family = style.fontFamily?.toLowerCase();
    if (family == null || !_monospaceFamilies.contains(family)) return null;
    final bold = style.fontWeight == pw.FontWeight.bold;
    final italic = style.fontStyle == pw.FontStyle.italic;
    if (bold && italic) {
      return _courierBoldOblique ??= pw.Font.courierBoldOblique();
    }
    if (bold) return _courierBold ??= pw.Font.courierBold();
    if (italic) return _courierOblique ??= pw.Font.courierOblique();
    return _courier ??= pw.Font.courier();
  }

  /// Extra inter-line spacing to reach the CSS line height. `pdf` lines are
  /// already about 1.15em tall (ascent + descent).
  double? _lineSpacing(CSSStyle style) {
    final fontSize = style.fontSize ?? 12;
    final target = style.lineHeight ??
        (style.lineHeightFactor != null
            ? style.lineHeightFactor! * fontSize
            : null);
    if (target == null) return null;
    return math.max(0, target - fontSize * 1.15);
  }

  pw.TextStyle _mapTextStyle(CSSStyle style) {
    final font = _fontFor(style);
    return pw.TextStyle(
      color: style.color,
      fontSize: style.fontSize,
      fontWeight: style.fontWeight,
      fontStyle: style.fontStyle,
      font: font,
      fontBold: font,
      fontItalic: font,
      fontBoldItalic: font,
      decoration: style.textDecoration,
      decorationColor: style.textDecorationColor,
      decorationStyle: style.textDecorationStyle,
      letterSpacing: style.letterSpacing,
      fontFallback: fontFallback,
      lineSpacing: _lineSpacing(style),
      background: style.backgroundColor != null
          ? pw.BoxDecoration(color: style.backgroundColor)
          : null,
    );
  }

  /// Renders a MathML `<math>` element (see [MathMLBuilder]).
  MathBox _buildMath(LayoutNode node) => MathMLBuilder(
        textStyle: _mapTextStyle(node.style),
        fontFallback: fontFallback,
      ).build(node, display: _isBlockMath(node));

  /// `<math display="block">` (case-insensitive) or CSS `display: block`.
  bool _isBlockMath(LayoutNode node) =>
      MathMLBuilder.isDisplayBlock(node) || node.style.display == Display.block;

  // ---------------------------------------------------------------------------
  // Specific blocks
  // ---------------------------------------------------------------------------

  Future<pw.Widget> _buildImage(LayoutNode node) async {
    return await image_builder.buildImage(node);
  }

  Future<_Block?> _buildPreBlock(LayoutNode node) async {
    final ctx = _InlineContext();
    for (final child in node.children) {
      await _collectInline(child, ctx, null);
    }
    // Drop a single trailing newline, as browsers do.
    var spans = ctx.spans;
    if (spans.isNotEmpty && spans.last is pw.TextSpan) {
      final last = spans.last as pw.TextSpan;
      final text = last.text ?? '';
      if (text.endsWith('\n')) {
        spans = [
          ...spans.sublist(0, spans.length - 1),
          pw.TextSpan(
              text: text.substring(0, text.length - 1),
              style: last.style,
              annotation: last.annotation),
        ];
      }
    }
    spans = _nbspToSpace(spans);
    if (spans.isEmpty) return _decorateBlock(node, const _Flow([], 0, 0));

    // Chunk by lines so long listings can break across pages.
    final chunks =
        _spanLength(spans) > 2000 ? _splitSpans(spans, _chunkChars) : [spans];
    final widgets = chunks
        .map((chunk) => pw.RichText(
              overflow: pw.TextOverflow.span,
              softWrap: node.style.whiteSpace != WhiteSpace.pre,
              text: pw.TextSpan(children: chunk),
              textAlign: node.style.textAlign ?? pw.TextAlign.left,
            ))
        .toList();
    return _decorateBlock(node, _Flow(widgets, 0, 0));
  }

  // ---------------------------------------------------------------------------
  // Lists
  // ---------------------------------------------------------------------------

  Future<_Block?> _buildList(LayoutNode node) async {
    final style = node.style;
    final isOrdered = node.tagName == 'ol';
    final reversed = node.attributes.containsKey('reversed');
    final items = node.children.where((c) => c.tagName == 'li').toList();

    var counter = int.tryParse(node.attributes['start'] ?? '') ??
        (reversed ? items.length : 1);

    final defaultBullet = const ['disc', 'circle', 'square'][_listDepth % 3];
    final type = style.listStyleType ?? (isOrdered ? 'decimal' : defaultBullet);
    final indent = style.padding?.left ?? 30.0;

    if (!isOrdered) _listDepth++;
    final blocks = <_Block>[];
    try {
      for (final child in node.children) {
        if (child.display == Display.none) continue;
        if (child.tagName != 'li') {
          if (child.tagName == '#text') continue;
          final b = await _buildBlockNode(child);
          if (b != null) {
            blocks.add(_Block(
                b.widgets
                    .map((w) => pw.Padding(
                        padding: pw.EdgeInsets.only(left: indent), child: w))
                    .toList(),
                marginTop: b.marginTop,
                marginBottom: b.marginBottom));
          }
          continue;
        }

        final explicit = int.tryParse(child.attributes['value'] ?? '');
        if (explicit != null) counter = explicit;
        // Task-list items (`<li><input type=checkbox>`) show only the box.
        final firstContent = child.children.firstWhere(
            (c) => c.tagName != '#text' || (c.text?.trim().isNotEmpty ?? false),
            orElse: () => child);
        final isTask = firstContent.tagName == 'input' &&
            firstContent.attributes['type'] == 'checkbox';
        final itemType = isTask ? 'none' : (child.style.listStyleType ?? type);
        final marker = _buildMarker(itemType, counter, child.style);
        counter += reversed ? -1 : 1;

        final flow = _join(await _buildFlow(child.children, child.style));
        final content = flow.widgets.isEmpty
            ? <pw.Widget>[
                pw.SizedBox(height: (child.style.fontSize ?? 12) * 1.15)
              ]
            : flow.widgets;

        final tableRows = <pw.TableRow>[];
        for (var i = 0; i < content.length; i++) {
          tableRows.add(pw.TableRow(children: [
            i == 0 ? marker : pw.SizedBox(),
            content[i],
          ]));
        }
        final item = pw.Table(
          columnWidths: {
            0: pw.FixedColumnWidth(indent),
            1: const pw.FlexColumnWidth(),
          },
          children: tableRows,
        );
        blocks.add(
            _Block([item], marginTop: flow.top, marginBottom: flow.bottom));
      }
    } finally {
      if (!isOrdered) _listDepth--;
    }

    final joined = _join(blocks);
    return _Block(
      joined.widgets.map((w) => _horizontalMargins(w, style)).toList(),
      marginTop: math.max(style.margin?.top ?? 0, joined.top),
      marginBottom: math.max(style.margin?.bottom ?? 0, joined.bottom),
    );
  }

  pw.Widget _buildMarker(String type, int index, CSSStyle itemStyle) {
    final fontSize = itemStyle.fontSize ?? 12;
    final color =
        tagStyle.bulletListIconColor ?? itemStyle.color ?? PdfColors.black;
    // Match the first line's height so the marker sits on its baseline.
    final lineHeight = fontSize * 1.15 + (_lineSpacing(itemStyle) ?? 0);

    pw.Widget shape(pw.BoxShape boxShape, {bool filled = true}) {
      final size = fontSize * 0.36;
      return pw.Container(
        height: lineHeight,
        alignment: pw.Alignment.centerRight,
        padding: pw.EdgeInsets.only(right: fontSize * 0.5),
        child: pw.Container(
          width: size,
          height: size,
          decoration: pw.BoxDecoration(
            color: filled ? color : null,
            border: filled ? null : pw.Border.all(color: color, width: 0.7),
            shape: boxShape,
          ),
        ),
      );
    }

    switch (type) {
      case 'none':
        return pw.SizedBox();
      case 'disc':
        return shape(pw.BoxShape.circle);
      case 'circle':
        return shape(pw.BoxShape.circle, filled: false);
      case 'square':
        return shape(pw.BoxShape.rectangle);
    }

    final label = '${_formatCounter(type, index)}.';
    final base = _mapTextStyle(itemStyle.merge(const CSSStyle(
        textDecoration: pw.TextDecoration.none, backgroundColor: null)));
    return pw.Padding(
      padding: pw.EdgeInsets.only(right: fontSize * 0.4),
      child: pw.Text(
        label,
        textAlign: pw.TextAlign.right,
        style: tagStyle.listIndexStyle != null
            ? base.merge(tagStyle.listIndexStyle)
            : base,
      ),
    );
  }

  String _formatCounter(String type, int n) {
    switch (type) {
      case 'lower-alpha':
      case 'lower-latin':
        return _alpha(n).toLowerCase();
      case 'upper-alpha':
      case 'upper-latin':
        return _alpha(n);
      case 'lower-roman':
        return _roman(n).toLowerCase();
      case 'upper-roman':
        return _roman(n);
      case 'lower-greek':
        const greek = 'αβγδεζηθικλμνξοπρστυφχψω';
        return n >= 1 && n <= greek.length ? greek[n - 1] : '$n';
      case 'decimal-leading-zero':
        return n.toString().padLeft(2, '0');
      default:
        return '$n';
    }
  }

  String _alpha(int n) {
    if (n <= 0) return '$n';
    var value = n;
    final buf = StringBuffer();
    while (value > 0) {
      value--;
      buf.write(String.fromCharCode(65 + value % 26));
      value ~/= 26;
    }
    return buf.toString().split('').reversed.join();
  }

  String _roman(int n) {
    if (n <= 0 || n >= 4000) return '$n';
    const values = [1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1];
    const symbols = [
      'M',
      'CM',
      'D',
      'CD',
      'C',
      'XC',
      'L',
      'XL',
      'X',
      'IX',
      'V',
      'IV',
      'I'
    ];
    var value = n;
    final buf = StringBuffer();
    for (var i = 0; i < values.length; i++) {
      while (value >= values[i]) {
        buf.write(symbols[i]);
        value -= values[i];
      }
    }
    return buf.toString();
  }

  // ---------------------------------------------------------------------------
  // Checkbox
  // ---------------------------------------------------------------------------

  pw.Widget _buildCheckbox(LayoutNode node) {
    final bool checked = node.attributes.containsKey('checked');

    // Priority 1: Use custom checkbox builder if provided
    if (tagStyle.checkboxBuilder != null) {
      return tagStyle.checkboxBuilder!(checked);
    }

    final size = tagStyle.checkboxSize;
    final checkedColor = tagStyle.checkedIconColor ?? PdfColors.blue;
    final uncheckedColor = tagStyle.uncheckedIconColor ?? PdfColors.white;

    return pw.Container(
      width: size,
      height: size,
      margin: const pw.EdgeInsets.only(right: 4),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.black, width: 1.5),
        color: checked ? checkedColor : uncheckedColor,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(2)),
      ),
      child: checked
          ? pw.Center(
              child: pw.Text(
                'X',
                style: pw.TextStyle(
                  fontSize: size * 0.7,
                  color: PdfColors.white,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
            )
          : null,
    );
  }

  // ---------------------------------------------------------------------------
  // Flex
  // ---------------------------------------------------------------------------

  Future<List<pw.Widget>> _buildFlex(LayoutNode node) async {
    final style = node.style;
    final isRow = style.flexDirection != FlexDirection.column &&
        style.flexDirection != FlexDirection.columnReverse;

    if (isRow) _rowDepth++;
    final childrenWidgets = <pw.Widget>[];
    try {
      for (final child in node.children) {
        if (child.display == Display.none) continue;
        List<pw.Widget> built;
        if (_isInlineLevel(child)) {
          built = await _buildInlineRun([child], style);
        } else {
          final block = await _buildBlockNode(child);
          built = block?.widgets ?? const [];
        }
        if (built.isEmpty) continue;
        pw.Widget childWidget = built.length == 1
            ? built.first
            : pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: built);

        final grow = child.style.flexGrow ?? 0;
        if (grow > 0) {
          childWidget = pw.Expanded(child: childWidget, flex: grow);
        } else if (isRow && child.style.width == null) {
          // CSS flex items shrink to fit (flex-shrink: 1).
          childWidget = pw.Flexible(child: childWidget);
        }
        childrenWidgets.add(childWidget);
      }
    } finally {
      if (isRow) _rowDepth--;
    }

    pw.MainAxisAlignment mainAlign;
    switch (style.justifyContent) {
      case JustifyContent.center:
        mainAlign = pw.MainAxisAlignment.center;
        break;
      case JustifyContent.spaceAround:
        mainAlign = pw.MainAxisAlignment.spaceAround;
        break;
      case JustifyContent.spaceBetween:
        mainAlign = pw.MainAxisAlignment.spaceBetween;
        break;
      case JustifyContent.spaceEvenly:
        mainAlign = pw.MainAxisAlignment.spaceEvenly;
        break;
      case JustifyContent.flexEnd:
        mainAlign = pw.MainAxisAlignment.end;
        break;
      default:
        mainAlign = pw.MainAxisAlignment.start;
    }

    pw.CrossAxisAlignment crossAlign;
    switch (style.alignItems) {
      case AlignItems.center:
        crossAlign = pw.CrossAxisAlignment.center;
        break;
      case AlignItems.flexEnd:
        crossAlign = pw.CrossAxisAlignment.end;
        break;
      case AlignItems.flexStart:
      case AlignItems.baseline:
        crossAlign = pw.CrossAxisAlignment.start;
        break;
      default:
        // CSS default is stretch; in a row that needs a bounded height, so
        // fall back to start.
        crossAlign =
            isRow ? pw.CrossAxisAlignment.start : pw.CrossAxisAlignment.stretch;
    }

    final reverse = style.flexDirection == FlexDirection.rowReverse ||
        style.flexDirection == FlexDirection.columnReverse;
    final flexWidget = pw.Flex(
      direction: isRow ? pw.Axis.horizontal : pw.Axis.vertical,
      mainAxisAlignment: mainAlign,
      crossAxisAlignment: crossAlign,
      children: reverse ? childrenWidgets.reversed.toList() : childrenWidgets,
    );

    return [
      _horizontalMargins(
          pw.Container(
            width: style.width,
            height: style.height,
            padding: style.padding,
            decoration: _boxDecoration(style),
            child: flexWidget,
          ),
          style)
    ];
  }

  // ---------------------------------------------------------------------------
  // Tables
  // ---------------------------------------------------------------------------

  Future<List<pw.Widget>> _buildTable(LayoutNode node) async {
    final rowNodes = <LayoutNode>[];
    final headerRows = <LayoutNode>{};
    final captions = <LayoutNode>[];
    for (final child in node.children) {
      if (child.display == Display.none) continue;
      if (child.tagName == 'tr') {
        rowNodes.add(child);
      } else if (child.tagName == 'caption') {
        captions.add(child);
      } else if (child.tagName == 'thead' ||
          child.tagName == 'tbody' ||
          child.tagName == 'tfoot') {
        for (final grandChild in child.children) {
          if (grandChild.tagName == 'tr' &&
              grandChild.display != Display.none) {
            rowNodes.add(grandChild);
            if (child.tagName == 'thead') headerRows.add(grandChild);
          }
        }
      }
    }
    if (rowNodes.isEmpty) return const [];

    // Place cells on a grid, honouring colspan/rowspan.
    final grid = <List<_GridCell?>>[];
    final occupied = <int, Set<int>>{};
    var columnCount = 0;
    var hasSpans = false;
    for (var r = 0; r < rowNodes.length; r++) {
      final cells = rowNodes[r]
          .children
          .where((c) => c.tagName == 'td' || c.tagName == 'th')
          .where((c) => c.display != Display.none)
          .toList();
      final rowCells = <_GridCell?>[];
      var col = 0;
      for (final cell in cells) {
        while (occupied[r]?.contains(col) ?? false) {
          col++;
        }
        final colSpan =
            (int.tryParse(cell.attributes['colspan'] ?? '') ?? 1).clamp(1, 50);
        final rowSpan =
            (int.tryParse(cell.attributes['rowspan'] ?? '') ?? 1).clamp(1, 500);
        if (colSpan > 1 || rowSpan > 1) hasSpans = true;
        final placed = _GridCell(
            cell, col, colSpan, math.min(rowSpan, rowNodes.length - r));
        while (rowCells.length < col) {
          rowCells.add(null);
        }
        rowCells.add(placed);
        for (var rr = r + 1; rr < r + rowSpan && rr < rowNodes.length; rr++) {
          for (var cc = col; cc < col + colSpan; cc++) {
            (occupied[rr] ??= <int>{}).add(cc);
          }
        }
        col += colSpan;
      }
      final occupiedCols = occupied[r] ?? const <int>{};
      final end = [col, ...occupiedCols.map((c) => c + 1)].reduce(math.max);
      columnCount = math.max(columnCount, end);
      grid.add(rowCells);
    }
    if (columnCount == 0) return const [];

    // Column widths: explicit cell widths win, else weight by content.
    final explicit = List<double?>.filled(columnCount, null);
    final weights = List<double>.filled(columnCount, 1);
    final fixedLayout = node.style.tableLayout == TableLayout.fixed;
    for (final row in grid) {
      for (final cell in row) {
        if (cell == null) continue;
        final w = cell.node.style.width;
        if (cell.colSpan == 1 && w != null) {
          explicit[cell.col] ??= w;
        }
        if (!fixedLayout && cell.colSpan == 1) {
          final len = _textLength(cell.node).toDouble();
          weights[cell.col] = math.max(
              weights[cell.col], math.sqrt(math.max(len, 1)).clamp(1, 12));
        }
      }
    }
    // Span mode lays rows out with flex widths only, so explicit widths (in
    // points) are converted into the same flex units as the content
    // weights, assuming the table spans a typical page content width.
    final assumedWidth = node.style.width ?? node.style.maxWidth ?? 480.0;
    final explicitTotal =
        explicit.whereType<double>().fold<double>(0, (a, b) => a + b);
    var flexTotal = 0.0;
    for (var c = 0; c < columnCount; c++) {
      if (explicit[c] == null) flexTotal += weights[c];
    }
    final pointsPerFlex = flexTotal > 0
        ? math.max(40.0, assumedWidth - explicitTotal) / flexTotal
        : 1.0;
    double colFlex(int c) =>
        explicit[c] != null ? explicit[c]! / pointsPerFlex : weights[c];

    final borderSide = _tableBorderSide(node);
    final tableBorder = borderSide == null
        ? null
        : pw.TableBorder.all(
            color: borderSide.color,
            width: borderSide.width,
            style: borderSide.style);

    final cellPaddingAttr =
        double.tryParse(node.attributes['cellpadding'] ?? '');

    pw.EdgeInsets cellPadding(LayoutNode c) =>
        c.style.padding ??
        (c.tagName == 'th'
            ? tagStyle.tableHeaderPadding
            : tagStyle.tableCellPadding) ??
        (cellPaddingAttr != null
            ? pw.EdgeInsets.all(cellPaddingAttr * 0.75)
            : const pw.EdgeInsets.all(5));

    Future<pw.Widget> buildCell(_GridCell cell, LayoutNode row) async {
      final c = cell.node;
      final padding = cellPadding(c);
      final flow = _join(await _buildFlow(c.children, c.style));
      final content = flow.widgets.isEmpty
          ? pw.SizedBox()
          : flow.widgets.length == 1
              ? flow.widgets.first
              : pw.Column(
                  // Shrink-wrap, so the cell's vertical-align can place it.
                  mainAxisSize: pw.MainAxisSize.min,
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: flow.widgets);

      final hAlign = c.style.textAlign == pw.TextAlign.center
          ? 0.0
          : c.style.textAlign == pw.TextAlign.right
              ? 1.0
              : -1.0;
      // pdf's Alignment y axis points up: 1 is the top edge.
      final vAlign = switch (c.style.verticalAlign ?? row.style.verticalAlign) {
        VerticalAlign.top || VerticalAlign.baseline => 1.0,
        VerticalAlign.bottom => -1.0,
        _ => 0.0,
      };
      return pw.Container(
        padding: padding,
        alignment: pw.Alignment(hAlign, vAlign),
        decoration: pw.BoxDecoration(
          color: c.style.backgroundColor,
          border: c.style.resolvedBorder,
        ),
        child: content,
      );
    }

    final widgets = <pw.Widget>[];
    for (final caption in captions) {
      final flow = _join(await _buildFlow(caption.children, caption.style));
      if (flow.widgets.isNotEmpty) {
        widgets.add(pw.Container(
          width: _fullWidth,
          padding: const pw.EdgeInsets.only(bottom: 4),
          child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.center,
              children: flow.widgets),
        ));
      }
    }

    pw.BoxDecoration? rowDecoration(LayoutNode row) =>
        row.style.backgroundColor != null
            ? pw.BoxDecoration(color: row.style.backgroundColor)
            : null;

    if (!hasSpans) {
      final rows = <pw.TableRow>[];
      for (var r = 0; r < grid.length; r++) {
        // A table row can't break across pages: rows with very long cells
        // are split into consecutive rows, one content chunk per cell.
        final longRow =
            grid[r].any((g) => g != null && _textLength(g.node) > 2000);
        if (longRow) {
          final parts = <List<pw.Widget>>[];
          for (var c = 0; c < columnCount; c++) {
            final cell = c < grid[r].length ? grid[r][c] : null;
            parts.add(cell == null
                ? const <pw.Widget>[]
                : _join(await _buildFlow(cell.node.children, cell.node.style))
                    .widgets);
          }
          pw.Widget chunkCell(int c, int k) {
            final cell = c < grid[r].length ? grid[r][c] : null;
            if (cell == null || k >= parts[c].length) return pw.SizedBox();
            final pad = cellPadding(cell.node);
            return pw.Container(
              padding: pw.EdgeInsets.only(
                left: pad.left,
                right: pad.right,
                top: k == 0 ? pad.top : 0,
                bottom: k == parts[c].length - 1 ? pad.bottom : 0,
              ),
              color: cell.node.style.backgroundColor,
              child: parts[c][k],
            );
          }

          final chunks = parts.map((p) => p.length).fold<int>(1, math.max);
          for (var k = 0; k < chunks; k++) {
            rows.add(pw.TableRow(
              decoration: rowDecoration(rowNodes[r]),
              children: [for (var c = 0; c < columnCount; c++) chunkCell(c, k)],
            ));
          }
          continue;
        }
        final cells = <pw.Widget>[];
        for (var c = 0; c < columnCount; c++) {
          final cell = c < grid[r].length ? grid[r][c] : null;
          cells.add(cell == null
              ? pw.SizedBox()
              : await buildCell(cell, rowNodes[r]));
        }
        rows.add(pw.TableRow(
          repeat: headerRows.contains(rowNodes[r]),
          decoration: rowDecoration(rowNodes[r]),
          children: cells,
        ));
      }
      final allExplicit = explicit.every((w) => w != null);
      widgets.add(pw.Table(
        border: tableBorder,
        defaultVerticalAlignment: pw.TableCellVerticalAlignment.full,
        tableWidth: allExplicit ? pw.TableWidth.min : pw.TableWidth.max,
        columnWidths: {
          for (var c = 0; c < columnCount; c++)
            c: explicit[c] != null
                ? pw.FixedColumnWidth(explicit[c]!)
                : pw.FlexColumnWidth(weights[c]),
        },
        children: rows,
      ));
    } else {
      // pw.Table has no cell spans: lay out each group of rows joined by
      // rowspans as one grid. Groups are separate widgets, so a page can
      // break between them but never through a rowspan.
      final columnFlex = [for (var c = 0; c < columnCount; c++) colFlex(c)];
      var start = 0;
      while (start < grid.length) {
        var end = start + 1;
        for (var r = start; r < end; r++) {
          for (final cell in grid[r]) {
            if (cell != null) end = math.max(end, r + cell.rowSpan);
          }
        }
        final cells = <SpanGridCell>[];
        for (var r = start; r < end; r++) {
          for (final cell in grid[r]) {
            if (cell == null) continue;
            cells.add(SpanGridCell(
              await buildCell(cell, rowNodes[r]),
              r - start,
              cell.col,
              math.min(cell.colSpan, columnCount - cell.col),
              cell.rowSpan,
            ));
          }
        }
        widgets.add(SpanGrid(
          columnFlex: columnFlex,
          rowCount: end - start,
          cells: cells,
          rowColors: [
            for (var r = start; r < end; r++) rowNodes[r].style.backgroundColor
          ],
          border: tableBorder == null ? null : borderSide,
        ));
        start = end;
      }
    }

    final style = node.style;
    return widgets.map((w) {
      pw.Widget out = w;
      if (style.width != null && _rowDepth == 0) {
        out = pw.SizedBox(width: style.width, child: out);
        out = _alignBlock(out, style);
      } else if (style.backgroundColor != null) {
        out = pw.Container(color: style.backgroundColor, child: out);
      }
      return _horizontalMargins(out, style);
    }).toList();
  }

  /// Grid line style for a table: from its CSS border / `border` attribute,
  /// none for `border="0"`/`border: none`, else a thin grey grid (the
  /// historical default, which keeps Markdown tables readable).
  pw.BorderSide? _tableBorderSide(LayoutNode node) {
    final attr = node.attributes['border'];
    final resolved = node.style.resolvedBorder;
    if (resolved != null) return resolved.top;
    final declaredNone = node.style.border != null ||
        (attr != null && (double.tryParse(attr) ?? 1) == 0);
    if (declaredNone) return null;
    return const pw.BorderSide(color: PdfColors.grey600, width: 0.5);
  }

  int _textLength(LayoutNode n) {
    var l = n.text?.trim().length ?? 0;
    for (final c in n.children) {
      l += _textLength(c);
    }
    return l;
  }
}

class _GridCell {
  final LayoutNode node;
  final int col;
  final int colSpan;
  final int rowSpan;

  _GridCell(this.node, this.col, this.colSpan, this.rowSpan);
}
